# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligent_scheduler', '0002_auto_20161003_2029'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='classduration',
        #    name='id',
        #),
        #migrations.AlterField(
        #    model_name='classduration',
        #    name='batch',
        #    field=models.CharField(choices=[(b'UG1', b'UG1'), (b'UG2', b'UG2'), (b'UG3', b'UG3'), (b'UG4', b'UG4')], default=b'UG1', max_length=4, primary_key=True, serialize=False),
        #),
        #migrations.AlterField(
        #    model_name='courses',
        #    name='cname',
        #    field=models.CharField(max_length=100, unique=True),
        #),
        #migrations.AlterField(
        #    model_name='courses',
        #    name='cshortname',
        #    field=models.CharField(max_length=6, unique=True),
        #),
        #migrations.AlterField(
        #    model_name='faculty',
        #    name='fshortname',
        #    field=models.CharField(max_length=4, unique=True),
        #),
        #migrations.AlterUniqueTogether(
        #    name='coursetaken',
        #    unique_together=set([('rollnumber', 'cid')]),
        #),
        #migrations.AlterUniqueTogether(
        #    name='coursetype',
        #    unique_together=set([('cid', 'batch', 'branch')]),
        #),
        #migrations.AlterUniqueTogether(
        #    name='teachingassistant',
        #    unique_together=set([('rollnumber', 'cid')]),
        #),
        migrations.RunSQL('alter table intelligent_scheduler_preferredfacultyhours add constraint ptimingcheck check (starttime<endtime);'),
    ]
