# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligent_scheduler', '0003_auto_20161004_0557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classduration',
            name='id',
        ),
        migrations.AlterField(
            model_name='classduration',
            name='batch',
            field=models.CharField(choices=[('UG1', 'UG1'), ('UG2', 'UG2'), ('UG3', 'UG3'), ('UG4', 'UG4')], default='UG1', max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courses',
            name='cname',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='cshortname',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='batch',
            field=models.CharField(choices=[('UG1', 'UG1'), ('UG2', 'UG2'), ('UG3', 'UG3'), ('UG4', 'UG4')], default='UG1', max_length=4),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE')], default='CSE', max_length=4),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='course_type',
            field=models.CharField(choices=[('C', 'Core Course'), ('FC', 'Flexi Core Course'), ('ITE', 'IT Elective')], max_length=4),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='fshortname',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='lunchbreak',
            name='batch',
            field=models.CharField(choices=[('UG1', 'UG1'), ('UG2', 'UG2'), ('UG3', 'UG3'), ('UG4', 'UG4')], default='UG1', max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='preferredfacultyhours',
            name='preferred_day',
            field=models.CharField(choices=[('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], default='MON', max_length=3),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(choices=[('UG1', 'UG1'), ('UG2', 'UG2'), ('UG3', 'UG3'), ('UG4', 'UG4')], default='UG1', max_length=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE')], default='CSE', max_length=4),
        ),
        migrations.AlterUniqueTogether(
            name='coursetaken',
            unique_together=set([('rollnumber', 'cid')]),
        ),
        migrations.AlterUniqueTogether(
            name='coursetype',
            unique_together=set([('cid', 'batch', 'branch')]),
        ),
        migrations.AlterUniqueTogether(
            name='teachingassistant',
            unique_together=set([('rollnumber', 'cid')]),
        ),
    ]
